### PR TITLE
Feature: basic route crud with k8s cluster

### PR DESCRIPTION
**Pull request by KONY128**

### CODE REVIEW

**Review by KONY128 — COMMENTED** [review]
all checked

**Comment by linxuyalun** [comment]
I would like that you show me how it works  and introduce the code first

**Comment by linxuyalun** [comment]
Overall, the code looks good to me, and I miss the details. I will investigate more time after you introducing the code

**Comment by KONY128** [comment]
Ops, 6a9ea58 and 5e0ce5a are mine, sorry

**Review by KONY128 — COMMENTED** [review]
all checked

**Pull request merged**
